import flet as ft

class Dropdowns:
    def __init__(self) -> None:
        self.genres = ft.Dropdown(
                options = [
                    ft.dropdown.Option('None'),
                    ft.dropdown.Option("Action"),
                    ft.dropdown.Option("Adventure"),
                    ft.dropdown.Option("Anthropomorphic"),
                    ft.dropdown.Option("Avant Garde"),
                    ft.dropdown.Option("Cars"),
                    ft.dropdown.Option("CGDCT"),
                    ft.dropdown.Option("Childcare"),
                    ft.dropdown.Option("Comedy"),
                    ft.dropdown.Option("Comic"),
                    ft.dropdown.Option("Crime"),
                    ft.dropdown.Option("Delinquents"),
                    ft.dropdown.Option("Dementia"),
                    ft.dropdown.Option("Demons"),
                    ft.dropdown.Option("Detective"),
                    ft.dropdown.Option("Drama"),
                    ft.dropdown.Option("Dub"),
                    ft.dropdown.Option("Family"),
                    ft.dropdown.Option("Fantasy"),
                    ft.dropdown.Option("Gag Humor"),
                    ft.dropdown.Option("Game"),
                    ft.dropdown.Option("Gourmet"),
                    ft.dropdown.Option("Harem"),
                    ft.dropdown.Option("High Stakes Game"),
                    ft.dropdown.Option("Historical"),
                    ft.dropdown.Option("Horror"),
                    ft.dropdown.Option("Isekai"),
                    ft.dropdown.Option("Iyashikei"),
                    ft.dropdown.Option("Josei"),
                    ft.dropdown.Option("Kids"),
                    ft.dropdown.Option("Magic"),
                    ft.dropdown.Option("Mahou Shoujo"),
                    ft.dropdown.Option("Martial Arts"),
                    ft.dropdown.Option("Mecha"),
                    ft.dropdown.Option("Medical"),
                    ft.dropdown.Option("Military"),
                    ft.dropdown.Option("Music"),
                    ft.dropdown.Option("Mystery"),
                    ft.dropdown.Option("Mythology"),
                    ft.dropdown.Option("Organized Crime"),
                    ft.dropdown.Option("Parody"),
                    ft.dropdown.Option("Performing Arts"),
                    ft.dropdown.Option("Pets"),
                    ft.dropdown.Option("Police"),
                    ft.dropdown.Option("Psychological"),
                    ft.dropdown.Option("Racing"),
                    ft.dropdown.Option("Reincarnation"),
                    ft.dropdown.Option("Romance"),
                    ft.dropdown.Option("Romantic Subtext"),
                    ft.dropdown.Option("Samurai"),
                    ft.dropdown.Option("School"),
                    ft.dropdown.Option("Sci-Fi"),
                    ft.dropdown.Option("Seinen"),
                    ft.dropdown.Option("Shoujo"),
                    ft.dropdown.Option("Shoujo Ai"),
                    ft.dropdown.Option("Shounen"),
                    ft.dropdown.Option("Showbiz"),
                    ft.dropdown.Option("Slice of Life"),
                    ft.dropdown.Option("Space"),
                    ft.dropdown.Option("Sports"),
                    ft.dropdown.Option("Strategy Game"),
                    ft.dropdown.Option("Super Power"),
                    ft.dropdown.Option("Supernatural"),
                    ft.dropdown.Option("Survival"),
                    ft.dropdown.Option("Suspense"),
                    ft.dropdown.Option("Team Sports"),
                    ft.dropdown.Option("Thriller"),
                    ft.dropdown.Option("Time Travel"),
                    ft.dropdown.Option("Vampire"),
                    ft.dropdown.Option("Video Game"),
                    ft.dropdown.Option("Visual Arts"),
                    ft.dropdown.Option("Work Life"),
                    ft.dropdown.Option("Workplace"),
                ],
                value = 'None',
                label = 'Genre',
                width = 199
                )
        self.years = ft.Dropdown(
                options = [
                    ft.dropdown.Option('None'),
                    ft.dropdown.Option("1999"),
                    ft.dropdown.Option("2000"),
                    ft.dropdown.Option("2001"),
                    ft.dropdown.Option("2002"),
                    ft.dropdown.Option("2003"),
                    ft.dropdown.Option("2004"),
                    ft.dropdown.Option("2005"),
                    ft.dropdown.Option("2006"),
                    ft.dropdown.Option("2007"),
                    ft.dropdown.Option("2008"),
                    ft.dropdown.Option("2009"),
                    ft.dropdown.Option("2010"),
                    ft.dropdown.Option("2011"),
                    ft.dropdown.Option("2012"),
                    ft.dropdown.Option("2013"),
                    ft.dropdown.Option("2014"),
                    ft.dropdown.Option("2015"),
                    ft.dropdown.Option("2016"),
                    ft.dropdown.Option("2017"),
                    ft.dropdown.Option("2018"),
                    ft.dropdown.Option("2019"),
                    ft.dropdown.Option("2020"),
                    ft.dropdown.Option("2021"),
                    ft.dropdown.Option("2022"),
                    ft.dropdown.Option("2023"),
                    ft.dropdown.Option("2024"),
                ],
                value = 'None',
                label = 'Year',
                width = 130
                )
        self.language = ft.Dropdown(
                options = [
                    ft.dropdown.Option("None"),
                    ft.dropdown.Option("Sub"),
                    ft.dropdown.Option("Dub"),
                ],
                value = 'None',
                label = 'Language',
                width = 110
                )
        self.season = ft.Dropdown(
                options = [
                    ft.dropdown.Option("None"),
                    ft.dropdown.Option("Spring"),
                    ft.dropdown.Option("Summer"),
                    ft.dropdown.Option("Fall"),
                    ft.dropdown.Option("Winter"),
                ],
                value = 'None',
                label = 'Season',
                width = 110
                )